const MQTT = {
  'SUCCESS': 0,
  'QOS_0': 0,
  'QOS_1': 1,
  'QOS_2': 2,
  'NO_SUBSCRIPTION': 17,
  'IMP_SPEC_ERROR': 131,
  'BAD_USER_PASS': 134,
  'NOT_AUTHORIZED': 135,
  'SERVER_UNAVAILABLE': 136,
  'TOPIC_INVALID': 143,
  'WILL_TOPIC_INVALID': 144,
  'PACKET_TOO_LARGE': 149,
  'PAYLOAD_INVALID': 153,
  'QOS_NOT_SUPPORTED': 155
};

module.exports = MQTT;
